/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as talosNameServiceSol from "./TalosNameService.sol";
export { MitosToken__factory } from "./MitosToken__factory";
export { TalosRegistry__factory } from "./TalosRegistry__factory";
