/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITalosRegistry } from "./ITalosRegistry";
export type { TalosNameService } from "./TalosNameService";
