/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITalosRegistry__factory } from "./ITalosRegistry__factory";
export { TalosNameService__factory } from "./TalosNameService__factory";
