/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITalosRegistry,
  ITalosRegistryInterface,
} from "../../../src/TalosNameService.sol/ITalosRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "talosId",
        type: "uint256",
      },
    ],
    name: "creatorOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITalosRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ITalosRegistryInterface {
    return new Interface(_abi) as ITalosRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITalosRegistry {
    return new Contract(address, _abi, runner) as unknown as ITalosRegistry;
  }
}
