/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as talosNameServiceSol from "./TalosNameService.sol";
export type { talosNameServiceSol };
export type { MitosToken } from "./MitosToken";
export type { TalosRegistry } from "./TalosRegistry";
