/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TalosRegistry {
  export type PatronStruct = {
    creatorShare: BigNumberish;
    investorShare: BigNumberish;
    treasuryShare: BigNumberish;
    creatorAddr: AddressLike;
    investorAddr: AddressLike;
    treasuryAddr: AddressLike;
  };

  export type PatronStructOutput = [
    creatorShare: bigint,
    investorShare: bigint,
    treasuryShare: bigint,
    creatorAddr: string,
    investorAddr: string,
    treasuryAddr: string
  ] & {
    creatorShare: bigint;
    investorShare: bigint;
    treasuryShare: bigint;
    creatorAddr: string;
    investorAddr: string;
    treasuryAddr: string;
  };

  export type KernelStruct = {
    approvalThreshold: BigNumberish;
    gtmBudget: BigNumberish;
    minPatronPulse: BigNumberish;
  };

  export type KernelStructOutput = [
    approvalThreshold: bigint,
    gtmBudget: bigint,
    minPatronPulse: bigint
  ] & { approvalThreshold: bigint; gtmBudget: bigint; minPatronPulse: bigint };

  export type PulseStruct = {
    totalSupply: BigNumberish;
    priceUsdCents: BigNumberish;
    tokenSymbol: string;
  };

  export type PulseStructOutput = [
    totalSupply: bigint,
    priceUsdCents: bigint,
    tokenSymbol: string
  ] & { totalSupply: bigint; priceUsdCents: bigint; tokenSymbol: string };

  export type TalosStruct = {
    id: BigNumberish;
    name: string;
    category: string;
    description: string;
    creator: AddressLike;
    patron: TalosRegistry.PatronStruct;
    kernel: TalosRegistry.KernelStruct;
    pulse: TalosRegistry.PulseStruct;
    createdAt: BigNumberish;
    active: boolean;
  };

  export type TalosStructOutput = [
    id: bigint,
    name: string,
    category: string,
    description: string,
    creator: string,
    patron: TalosRegistry.PatronStructOutput,
    kernel: TalosRegistry.KernelStructOutput,
    pulse: TalosRegistry.PulseStructOutput,
    createdAt: bigint,
    active: boolean
  ] & {
    id: bigint;
    name: string;
    category: string;
    description: string;
    creator: string;
    patron: TalosRegistry.PatronStructOutput;
    kernel: TalosRegistry.KernelStructOutput;
    pulse: TalosRegistry.PulseStructOutput;
    createdAt: bigint;
    active: boolean;
  };
}

export interface TalosRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PROTOCOL_FEE_BPS"
      | "acceptOwnership"
      | "createTalos"
      | "creatorOf"
      | "deactivateTalos"
      | "getTalos"
      | "isActive"
      | "nextTalosId"
      | "owner"
      | "pendingOwner"
      | "protocolFeeBps"
      | "protocolWallet"
      | "renounceOwnership"
      | "setProtocolWallet"
      | "transferOwnership"
      | "updateKernel"
      | "updatePatron"
      | "updatePulse"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PatronUpdated"
      | "ProtocolWalletUpdated"
      | "TalosCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTalos",
    values: [
      string,
      string,
      string,
      TalosRegistry.PatronStruct,
      TalosRegistry.KernelStruct,
      TalosRegistry.PulseStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateTalos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTalos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTalosId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateKernel",
    values: [BigNumberish, TalosRegistry.KernelStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePatron",
    values: [BigNumberish, TalosRegistry.PatronStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePulse",
    values: [BigNumberish, TalosRegistry.PulseStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTalos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creatorOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateTalos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTalos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTalosId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKernel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePatron",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePulse",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatronUpdatedEvent {
  export type InputTuple = [
    talosId: BigNumberish,
    creatorShare: BigNumberish,
    investorShare: BigNumberish,
    treasuryShare: BigNumberish
  ];
  export type OutputTuple = [
    talosId: bigint,
    creatorShare: bigint,
    investorShare: bigint,
    treasuryShare: bigint
  ];
  export interface OutputObject {
    talosId: bigint;
    creatorShare: bigint;
    investorShare: bigint;
    treasuryShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolWalletUpdatedEvent {
  export type InputTuple = [protocolWallet: AddressLike];
  export type OutputTuple = [protocolWallet: string];
  export interface OutputObject {
    protocolWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TalosCreatedEvent {
  export type InputTuple = [
    talosId: BigNumberish,
    creator: AddressLike,
    name: string
  ];
  export type OutputTuple = [talosId: bigint, creator: string, name: string];
  export interface OutputObject {
    talosId: bigint;
    creator: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TalosRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TalosRegistry;
  waitForDeployment(): Promise<this>;

  interface: TalosRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  createTalos: TypedContractMethod<
    [
      name: string,
      category: string,
      description: string,
      patron: TalosRegistry.PatronStruct,
      kernel: TalosRegistry.KernelStruct,
      pulse: TalosRegistry.PulseStruct
    ],
    [bigint],
    "nonpayable"
  >;

  creatorOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deactivateTalos: TypedContractMethod<
    [talosId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTalos: TypedContractMethod<
    [talosId: BigNumberish],
    [TalosRegistry.TalosStructOutput],
    "view"
  >;

  isActive: TypedContractMethod<[talosId: BigNumberish], [boolean], "view">;

  nextTalosId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  protocolWallet: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setProtocolWallet: TypedContractMethod<
    [protocolWallet_: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateKernel: TypedContractMethod<
    [talosId: BigNumberish, kernel: TalosRegistry.KernelStruct],
    [void],
    "nonpayable"
  >;

  updatePatron: TypedContractMethod<
    [talosId: BigNumberish, patron: TalosRegistry.PatronStruct],
    [void],
    "nonpayable"
  >;

  updatePulse: TypedContractMethod<
    [talosId: BigNumberish, pulse: TalosRegistry.PulseStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTalos"
  ): TypedContractMethod<
    [
      name: string,
      category: string,
      description: string,
      patron: TalosRegistry.PatronStruct,
      kernel: TalosRegistry.KernelStruct,
      pulse: TalosRegistry.PulseStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateTalos"
  ): TypedContractMethod<[talosId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTalos"
  ): TypedContractMethod<
    [talosId: BigNumberish],
    [TalosRegistry.TalosStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[talosId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextTalosId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolWallet"
  ): TypedContractMethod<[protocolWallet_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateKernel"
  ): TypedContractMethod<
    [talosId: BigNumberish, kernel: TalosRegistry.KernelStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePatron"
  ): TypedContractMethod<
    [talosId: BigNumberish, patron: TalosRegistry.PatronStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePulse"
  ): TypedContractMethod<
    [talosId: BigNumberish, pulse: TalosRegistry.PulseStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PatronUpdated"
  ): TypedContractEvent<
    PatronUpdatedEvent.InputTuple,
    PatronUpdatedEvent.OutputTuple,
    PatronUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolWalletUpdated"
  ): TypedContractEvent<
    ProtocolWalletUpdatedEvent.InputTuple,
    ProtocolWalletUpdatedEvent.OutputTuple,
    ProtocolWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TalosCreated"
  ): TypedContractEvent<
    TalosCreatedEvent.InputTuple,
    TalosCreatedEvent.OutputTuple,
    TalosCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PatronUpdated(uint256,uint32,uint32,uint32)": TypedContractEvent<
      PatronUpdatedEvent.InputTuple,
      PatronUpdatedEvent.OutputTuple,
      PatronUpdatedEvent.OutputObject
    >;
    PatronUpdated: TypedContractEvent<
      PatronUpdatedEvent.InputTuple,
      PatronUpdatedEvent.OutputTuple,
      PatronUpdatedEvent.OutputObject
    >;

    "ProtocolWalletUpdated(address)": TypedContractEvent<
      ProtocolWalletUpdatedEvent.InputTuple,
      ProtocolWalletUpdatedEvent.OutputTuple,
      ProtocolWalletUpdatedEvent.OutputObject
    >;
    ProtocolWalletUpdated: TypedContractEvent<
      ProtocolWalletUpdatedEvent.InputTuple,
      ProtocolWalletUpdatedEvent.OutputTuple,
      ProtocolWalletUpdatedEvent.OutputObject
    >;

    "TalosCreated(uint256,address,string)": TypedContractEvent<
      TalosCreatedEvent.InputTuple,
      TalosCreatedEvent.OutputTuple,
      TalosCreatedEvent.OutputObject
    >;
    TalosCreated: TypedContractEvent<
      TalosCreatedEvent.InputTuple,
      TalosCreatedEvent.OutputTuple,
      TalosCreatedEvent.OutputObject
    >;
  };
}
