/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TalosNameServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hasName"
      | "isNameAvailable"
      | "nameOf"
      | "registerName"
      | "resolveName"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NameRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "hasName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isNameAvailable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nameOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerName",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "resolveName", values: [string]): string;

  decodeFunctionResult(functionFragment: "hasName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNameAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nameOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveName",
    data: BytesLike
  ): Result;
}

export namespace NameRegisteredEvent {
  export type InputTuple = [talosId: BigNumberish, name: string];
  export type OutputTuple = [talosId: bigint, name: string];
  export interface OutputObject {
    talosId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TalosNameService extends BaseContract {
  connect(runner?: ContractRunner | null): TalosNameService;
  waitForDeployment(): Promise<this>;

  interface: TalosNameServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hasName: TypedContractMethod<[talosId: BigNumberish], [boolean], "view">;

  isNameAvailable: TypedContractMethod<[name: string], [boolean], "view">;

  nameOf: TypedContractMethod<[talosId: BigNumberish], [string], "view">;

  registerName: TypedContractMethod<
    [talosId: BigNumberish, name: string],
    [void],
    "nonpayable"
  >;

  resolveName: TypedContractMethod<[name: string], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hasName"
  ): TypedContractMethod<[talosId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isNameAvailable"
  ): TypedContractMethod<[name: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "nameOf"
  ): TypedContractMethod<[talosId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerName"
  ): TypedContractMethod<
    [talosId: BigNumberish, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveName"
  ): TypedContractMethod<[name: string], [bigint], "view">;

  getEvent(
    key: "NameRegistered"
  ): TypedContractEvent<
    NameRegisteredEvent.InputTuple,
    NameRegisteredEvent.OutputTuple,
    NameRegisteredEvent.OutputObject
  >;

  filters: {
    "NameRegistered(uint256,string)": TypedContractEvent<
      NameRegisteredEvent.InputTuple,
      NameRegisteredEvent.OutputTuple,
      NameRegisteredEvent.OutputObject
    >;
    NameRegistered: TypedContractEvent<
      NameRegisteredEvent.InputTuple,
      NameRegisteredEvent.OutputTuple,
      NameRegisteredEvent.OutputObject
    >;
  };
}
